// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDGVB07YMExQstGolch-cZIrSTpuojAuO8',
    appId: '1:163214469630:web:08fe2ebc779f536a8178af',
    messagingSenderId: '163214469630',
    projectId: 'trydentlabs-goglyder',
    authDomain: 'trydentlabs-goglyder.firebaseapp.com',
    storageBucket: 'trydentlabs-goglyder.firebasestorage.app',
    measurementId: 'G-QR616XZZ35',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBUJH-w7afuUjVC_AH7DqiaBcsXO4zrjYg',
    appId: '1:163214469630:android:f123785a4ad57d6e8178af',
    messagingSenderId: '163214469630',
    projectId: 'trydentlabs-goglyder',
    storageBucket: 'trydentlabs-goglyder.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDzbO0i0glmwBxqG0qBO2zmwnsmcREUS6o',
    appId: '1:163214469630:ios:8f68c75acee270e28178af',
    messagingSenderId: '163214469630',
    projectId: 'trydentlabs-goglyder',
    storageBucket: 'trydentlabs-goglyder.firebasestorage.app',
    iosBundleId: 'com.trydentlabs.goglyder.goGlyder',
  );
}
