android.useAndroidX=true
# Give Gradle more RAM (M3/M4 can handle it)
org.gradle.jvmargs=-Xmx4g -XX:+UseParallelGC

# Enable background "Daemon" to keep Gradle warm
org.gradle.daemon=true

# Run tasks in parallel (huge for multi-core Macs)
org.gradle.parallel=true

# Reuse previous build results
org.gradle.caching=true

# Only configure what is needed
org.gradle.configureondemand=true