// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC1vqxYcTwlCHx1uYsxtEW3GxE5RBu-gA8',
    appId: '1:937075343139:web:ee2bd594a69ebfeed01696',
    messagingSenderId: '937075343139',
    projectId: 'goglyder',
    authDomain: 'goglyder.firebaseapp.com',
    storageBucket: 'goglyder.firebasestorage.app',
    measurementId: 'G-BQ1M8L0TND',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAy5NNMXdtc6qCNSrmHZTzn6uLH06A-89M',
    appId: '1:937075343139:android:066a2ef7435e4db6d01696',
    messagingSenderId: '937075343139',
    projectId: 'goglyder',
    storageBucket: 'goglyder.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBkRpsKMGJmOlJUyByG2fbdaXilNYjKhfs',
    appId: '1:937075343139:ios:842b44a4d648ff47d01696',
    messagingSenderId: '937075343139',
    projectId: 'goglyder',
    storageBucket: 'goglyder.firebasestorage.app',
    iosBundleId: 'com.trydentlabs.goglyder.goGlyder',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBkRpsKMGJmOlJUyByG2fbdaXilNYjKhfs',
    appId: '1:937075343139:ios:842b44a4d648ff47d01696',
    messagingSenderId: '937075343139',
    projectId: 'goglyder',
    storageBucket: 'goglyder.firebasestorage.app',
    iosBundleId: 'com.trydentlabs.goglyder.goGlyder',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC1vqxYcTwlCHx1uYsxtEW3GxE5RBu-gA8',
    appId: '1:937075343139:web:9d62a051df6cb4a9d01696',
    messagingSenderId: '937075343139',
    projectId: 'goglyder',
    authDomain: 'goglyder.firebaseapp.com',
    storageBucket: 'goglyder.firebasestorage.app',
    measurementId: 'G-EJ6T733K5L',
  );
}
